### ISSUE TITLE
pcm scensor server: Using docker & granfana front-ended error

### ISSUE THREAD

**Issue by kimiliu666** [intel/pcm#679] opened 2024-02-20 07:06 UTC
Grafana is running,but no data on the page. The post request failed and the error message is :
A
Status: 500. Message: InfluxDB returned error: error parsing query: found \/, expected identifier, string, number, bool at line 1, char 316

I have tried the lateset master branch and the "202311 Release" code gz, both two ways result in the same error.

**Comment by kimiliu666** [comment] 2024-02-21 01:09
> are you using the start.sh script to start the containers and generate the dashboard?

Yes! # sudo sh start.sh http://10.143.208.232:9738

**Comment by rdementi** [comment] 2024-02-21 07:16
I tried the most recent version of pcm and grafana scripts (start.sh/stop.sh) from the master branch and the issue is not reproducible on my end. InfluxDB accepts the queries. Which version of pcm are you using?

**Comment by kimiliu666** [comment] 2024-02-21 08:18
> I tried the most recent version of pcm and grafana scripts (start.sh/stop.sh) from the master branch and the issue is not reproducible on my end. InfluxDB accepts the queries. Which version of pcm are you using?

I first tried master branch last day, but it didn't work. 
I have checked the containers with "docker ps ",influxdb and grafana are both running。
So I aslo tried  "202311 Release" :
https://github.com/intel/pcm/releases/tag/202311
Also result in the same error.

**Comment by kimiliu666** [comment] 2024-02-21 08:24
> > I tried the most recent version of pcm and grafana scripts (start.sh/stop.sh) from the master branch and the issue is not reproducible on my end. InfluxDB accepts the queries. Which version of pcm are you using?
> 
> I first tried master branch last day, but it didn't work. I have checked the containers with "docker ps ",influxdb and grafana are both running。 So I aslo tried "202311 Release" : https://github.com/intel/pcm/releases/tag/202311 Also result in the same error.

First ,with master branch, the docker cannnot start influxdb correctly, because the "network" word is at the wrong place, I fixed it and found you fixed it last day. @.@
But this front end error confused me for hours, and I cannot fix it by myself.

**Comment by rdementi** [comment] 2024-02-21 08:35
ok. Perhaps you can try to stop the containers (stop.sh), delete your old container volumes (rm -rf *_volume), use the most recent version from scratch? It works flawlessly for me

**Comment by rdementi** [comment] 2024-07-15 07:57
I believe this has been fixed in a recent version. If not, please re-open

**Closed by rdementi** 2024-07-15 07:57 UTC
