### ISSUE TITLE
pcm-202210 core dumped

### ISSUE THREAD

**Issue by dmitryluhtionov** [intel/pcm#507] opened 2023-02-10 14:37 UTC
```
CPU: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (2397.27-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x306f2  Family=0x6  Model=0x3f  Stepping=2
  Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0x7ffefbff<SSE3,PCLMULQDQ,DTES64,MON,DS_CPL,VMX,SMX,EST,TM2,SSSE3,SDBG,FMA,CX16,xTPR,PDCM,PCID,DCA,SSE4.1,SSE4.2,x2APIC,MOVBE,POPCNT,TSCDLT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x21<LAHF,ABM>
  Structured Extended Features=0x37ab<FSGSBASE,TSCADJ,BMI1,AVX2,SMEP,BMI2,ERMS,INVPCID,PQM,NFPUSG>
  Structured Extended Features3=0x9c000400<MD_CLEAR,IBPB,STIBP,L1DFL,SSBD>
  XSAVE Features=0x1<XSAVEOPT>
  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID,VID,PostIntr
  TSC: P-state invariant, performance statistics

# pcm-power

 Intel(r) Performance Counter Monitor (2022-10-19 10:53:25 +0200 ID=2ae6316f)

 Power Monitoring Utility

=====  Processor information  =====
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : no
Max CPUID level          : 15
CPU model number         : 63
Number of physical cores: 12
Number of logical cores: 24
Number of online logical cores: 24
Threads (logical cores) per physical core: 2
Num sockets: 2
Physical cores per socket: 6
Last level cache slices per socket: 6
Core PMU (perfmon) version: 3
Number of core PMU generic (programmable) counters: 4
Width of generic (programmable) counters: 48 bits
Number of core PMU fixed counters: 3
Width of fixed counters: 48 bits
Nominal core frequency: 2400000000 Hz
IBRS enabled in the kernel   : no
STIBP enabled in the kernel  : no
Package thermal spec power: 85 Watt; Package minimum power: 45 Watt; Package maximum power: 170 Watt;

ERROR: QPI LL monitoring device (0:7f:8:2) is missing. The QPI statistics will be incomplete or missing.
ERROR: QPI LL monitoring device (0:7f:9:2) is missing. The QPI statistics will be incomplete or missing.
Socket 0: 2 memory controllers detected with total number of 5 channels. 0 QPI ports detected. 0 M2M (mesh to memory) blocks detected. 1 Home Agents detected. 0 M3UPI blocks detected.
ERROR: QPI LL monitoring device (0:ff:8:2) is missing. The QPI statistics will be incomplete or missing.
ERROR: QPI LL monitoring device (0:ff:9:2) is missing. The QPI statistics will be incomplete or missing.
Socket 1: 2 memory controllers detected with total number of 5 channels. 0 QPI ports detected. 0 M2M (mesh to memory) blocks detected. 1 Home Agents detected. 0 M3UPI blocks detected.
Initializing RMIDs




MC counter group: 0
PCU counter group: 0
Your processor does not support frequency band statistics
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (DEBUG: caught signal to interrupt (DEBUG: caught signal to interrupt (DEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Abort trapDEBUG: caught signal to interrupt (Abort trapDEBUG: caught signal to interrupt (Abort trap).
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt (DEBUG: caught signal to interrupt (Abort trapAssertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Abort trapDEBUG: caught signal to interrupt (Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
).
DEBUG: caught signal to interrupt (DEBUG: caught signal to interrupt ().
Abort trap).
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
DEBUG: caught signal to interrupt ().
Abort trap).
Abort trapCleaning up
).
Abort trapDEBUG: caught signal to interrupt (Abort trapAbort trapCleaning up
Abort trap).
DEBUG: caught signal to interrupt (Cleaning up
Abort trap).
).
DEBUG: caught signal to interrupt (Abort trap).
).
Abort trapAbort trap).
Abort trapAbort trapCleaning up
).
Cleaning up
Assertion failed: (core_global_ctrl_value), function readAndAggregate, file /wrkdirs/usr/ports/sysutils/intel-pcm/work/pcm-202210/src/cpucounters.cpp, line 4553.
).
Abort trap).
Abort (core dumped)
```

**Comment by rdementi** [comment] 2023-02-10 17:04
duplicate of https://github.com/intel/pcm/issues/508

**Closed by rdementi** 2023-02-10 17:04 UTC
